[package]
name = "kb_mouse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rdev = { version = "0.5.3", features = ["unstable_grab"] }
enigo = "0.1.3"
exitcode = "1.1.2"
fslock = "0.2.1"
